# Generated by Django 3.2.4 on 2021-06-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20210630_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='closeDate',
        ),
    ]
