# Generated by Django 3.2.4 on 2021-06-30 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_remove_tournament_closedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='closeDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
