# Generated by Django 3.2.4 on 2021-06-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_closedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='size',
            field=models.IntegerField(choices=[(4, 4), (8, 8), (16, 16), (32, 32), (64, 64)], default='4'),
        ),
    ]
